repos:
  # general stuff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

      # Security
      - id: detect-private-key

  # markdown
  - repo: https://github.com/markdownlint/markdownlint.git
    rev: master
    hooks:
      - id: markdownlint_docker

  # security scans for infrastructure
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.1.20"
    hooks:
      - id: checkov
